#ifndef TYPES_WLF_KEYBOARD_H
#define TYPES_WLF_KEYBOARD_H

#include <stdint.h>

enum wlf_key {
    WLF_KEY_UNKNOWN = 0,

    WLF_KEY_SPACE,
    WLF_KEY_EXCLAM,
    WLF_KEY_QUOTEDBL,
    WLF_KEY_NUMBER,
    WLF_KEY_DOLLAR,
    WLF_KEY_PERCENT,
    WLF_KEY_AMPERSAND,
    WLF_KEY_APOSTROPHE,
    WLF_KEY_PAREN_LEFT,
    WLF_KEY_PAREN_RIGHT,
    WLF_KEY_ASTERISK,
    WLF_KEY_PLUS,
    WLF_KEY_COMMA,
    WLF_KEY_MINUS,
    WLF_KEY_PERIOD,
    WLF_KEY_SLASH,

    WLF_KEY_0, WLF_KEY_1, WLF_KEY_2, WLF_KEY_3, WLF_KEY_4,
    WLF_KEY_5, WLF_KEY_6, WLF_KEY_7, WLF_KEY_8, WLF_KEY_9,

    WLF_KEY_COLON,
    WLF_KEY_SEMICOLON,
    WLF_KEY_LESS,
    WLF_KEY_EQUAL,
    WLF_KEY_GREATER,
    WLF_KEY_QUESTION,
    WLF_KEY_AT,

    WLF_KEY_A, WLF_KEY_B, WLF_KEY_C, WLF_KEY_D, WLF_KEY_E,
    WLF_KEY_F, WLF_KEY_G, WLF_KEY_H, WLF_KEY_I, WLF_KEY_J,
    WLF_KEY_K, WLF_KEY_L, WLF_KEY_M, WLF_KEY_N, WLF_KEY_O,
    WLF_KEY_P, WLF_KEY_Q, WLF_KEY_R, WLF_KEY_S, WLF_KEY_T,
    WLF_KEY_U, WLF_KEY_V, WLF_KEY_W, WLF_KEY_X, WLF_KEY_Y,
    WLF_KEY_Z,

    WLF_KEY_ESCAPE,
    WLF_KEY_TAB,
    WLF_KEY_BACKSPACE,
    WLF_KEY_RETURN,
    WLF_KEY_INSERT,
    WLF_KEY_DELETE,

    WLF_KEY_LEFT,
    WLF_KEY_RIGHT,
    WLF_KEY_UP,
    WLF_KEY_DOWN,

    WLF_KEY_PAGE_UP,
    WLF_KEY_PAGE_DOWN,
    WLF_KEY_HOME,
    WLF_KEY_END,

    WLF_KEY_F1,  WLF_KEY_F2,  WLF_KEY_F3,  WLF_KEY_F4,
    WLF_KEY_F5,  WLF_KEY_F6,  WLF_KEY_F7,  WLF_KEY_F8,
    WLF_KEY_F9,  WLF_KEY_F10, WLF_KEY_F11, WLF_KEY_F12,
    WLF_KEY_F13, WLF_KEY_F14, WLF_KEY_F15, WLF_KEY_F16,
    WLF_KEY_F17, WLF_KEY_F18, WLF_KEY_F19, WLF_KEY_F20,
    WLF_KEY_F21, WLF_KEY_F22, WLF_KEY_F23, WLF_KEY_F24,

    WLF_KEY_SHIFT,
    WLF_KEY_CONTROL,
    WLF_KEY_ALT,
    WLF_KEY_META,
    WLF_KEY_CAPS_LOCK,
    WLF_KEY_NUM_LOCK,
    WLF_KEY_SCROLL_LOCK,
};

enum wlf_key_state {
	WLF_KEY_STATE_RELEASED = 0,
	WLF_KEY_STATE_PRESSED,
	WLF_KEY_STATE_REPEATED
};

struct wlf_repeat_info {
	uint32_t rate;
	uint32_t delay;
};

#endif // TYPES_WLF_KEYBOARD_H
